from pymongo import MongoClient

client = MongoClient()
db = client.data

db.data.insert({'schools':CAS,
                'classes' : [
                    "Advanced Honors Seminars (AHSEM-UA)",
                    American Studies - Social and Cultural Analysis (SCA-UA2),
                    Anthropology (ANTH-UA)
                    Asian/Pacific/American Studies - Social and Cultural Analysis (SCA-UA3)
                    CAS Scholars Program (SCHOL-UA)
                    Child/Adoles Mental Hlth Stds (CAMHS-UA)
                    Classics (CLASS-UA)
                    Collegiate Seminar Program (COSEM-UA)
                    Computer Science (CSCI-UA)
                    Dramatic Literature (DRLIT-UA)
                    Economics (ECON-UA)
                    English (ENGL-UA)
                    European and Mediterranean Studies 
                    (EURO-UA)
                    French (FREN-UA)
                    Freshman Honors Seminars (FRSEM-UA)
                    German (GERM-UA)
                    Hamilton Program (ALHAM-UA)
                    Hellenic Studies (HEL-UA)
                    International Relations (INTRL-UA)
                    Italian (ITAL-UA)
                    Latino Studies - Social and Cultural Analysis (SCA-UA5)
                    Linguistics (LING-UA)
                    Medieval & Renaissance Studies (MEDI-UA)
                    Middle Eastern and Islamic Studies 
                    (MEIS-UA)
                    Music (MUSIC-UA)
                    Non-Departmental (NODEP-UA)
                    Physics (PHYS-UA)
                    Pontif Univ. Cat-Chile Courses (PONT)
                    Psychology (PSYCH-UA)
                    Russian & Slavic Studies (RUSSN-UA)
                    Sociology (SOC-UA)
                    Africana Studies - Social and 
                    Cultural Analysis (SCA-UA1)
                    Animal Studies (ANST-UA)
                    Art History (ARTH-UA)
                    Biology (BIOL-UA)
                    Chemistry (CHEM-UA)
                    Child/Adoles Mental Hlth Stds (CAMS-UA)
                    College Core Curriculum (CORE-UA)
                    Comparative Literature (COLIT-UA)
                    Creative Writing (CRWRI-UA)
                    East Asian Studies (EAST-UA)
                    Engineering Pgm with Stevens (STVNS-UA)
                    Environmental Studies (ENVST-UA)
                    Expository Writing (EXPOS-UA)
                    Freshman Cohort Meeting (COHRT-UA)
                    Gender & Sexuality Studies - Social 
                    and Cultural Analysis (SCA-UA4)
                    Global Programs (GLBL-UA)
                    Hebrew & Judaic Studies (HBRJD-UA)
                    History (HIST-UA)
                    Irish Studies (IRISH-UA)
                    Journalism (JOUR-UA)
                    Law and Society (LWSOC-UA)
                    Math (MATH-UA)
                    Metropolitan Studies - Social 
                    and Cultural Analysis (SCA-UA6)
                    Morse Academic Plan (MAP) (MAP-UA)
                    Neural Science (NEURL-UA)
                    Philosophy (PHIL-UA)
                    Politics (POL-UA)
                    Portuguese (PORT-UA)
                    Religious Studies (RELST-UA)
                    Social and Cultural Analysis (SCA-UA)
                    Spanish (SPAN-UA)
                ]})
